// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "BCAIA_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvnrm_arma_mc
arma::vec dmvnrm_arma_mc(arma::mat const& x, arma::rowvec const& mean, arma::mat const& sigma, bool const logd);
RcppExport SEXP _BCAIA_dmvnrm_arma_mc(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec const& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool const >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnrm_arma_mc(x, mean, sigma, logd));
    return rcpp_result_gen;
END_RCPP
}
// dnormLog2
double dnormLog2(arma::vec x, double means, double sds);
RcppExport SEXP _BCAIA_dnormLog2(SEXP xSEXP, SEXP meansSEXP, SEXP sdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type means(meansSEXP);
    Rcpp::traits::input_parameter< double >::type sds(sdsSEXP);
    rcpp_result_gen = Rcpp::wrap(dnormLog2(x, means, sds));
    return rcpp_result_gen;
END_RCPP
}
// rgigRcpp
double rgigRcpp(double lam, double chi, double psi);
RcppExport SEXP _BCAIA_rgigRcpp(SEXP lamSEXP, SEXP chiSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type chi(chiSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(rgigRcpp(lam, chi, psi));
    return rcpp_result_gen;
END_RCPP
}
// seq_cpp
uvec seq_cpp(int locppid, int hicppid);
RcppExport SEXP _BCAIA_seq_cpp(SEXP locppidSEXP, SEXP hicppidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type locppid(locppidSEXP);
    Rcpp::traits::input_parameter< int >::type hicppid(hicppidSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_cpp(locppid, hicppid));
    return rcpp_result_gen;
END_RCPP
}
// mvrnormArma
arma::mat mvrnormArma(int n, arma::vec mu, arma::mat sigma);
RcppExport SEXP _BCAIA_mvrnormArma(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvrnormArma(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_inv
mat cpp_inv(mat A);
RcppExport SEXP _BCAIA_cpp_inv(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_inv(A));
    return rcpp_result_gen;
END_RCPP
}
// update_ystar
mat update_ystar(mat logY, mat logY1, int n, int J, mat RSS, double sig2);
RcppExport SEXP _BCAIA_update_ystar(SEXP logYSEXP, SEXP logY1SEXP, SEXP nSEXP, SEXP JSEXP, SEXP RSSSEXP, SEXP sig2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type logY(logYSEXP);
    Rcpp::traits::input_parameter< mat >::type logY1(logY1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    rcpp_result_gen = Rcpp::wrap(update_ystar(logY, logY1, n, J, RSS, sig2));
    return rcpp_result_gen;
END_RCPP
}
// update_sig2
double update_sig2(int n, int J, mat RSS, double a_sig, double b_sig);
RcppExport SEXP _BCAIA_update_sig2(SEXP nSEXP, SEXP JSEXP, SEXP RSSSEXP, SEXP a_sigSEXP, SEXP b_sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< double >::type a_sig(a_sigSEXP);
    Rcpp::traits::input_parameter< double >::type b_sig(b_sigSEXP);
    rcpp_result_gen = Rcpp::wrap(update_sig2(n, J, RSS, a_sig, b_sig));
    return rcpp_result_gen;
END_RCPP
}
// update_Q
mat update_Q(int J, int K, mat zeta, rowvec tau, mat phi, mat eeta, mat RSS, double sig2);
RcppExport SEXP _BCAIA_update_Q(SEXP JSEXP, SEXP KSEXP, SEXP zetaSEXP, SEXP tauSEXP, SEXP phiSEXP, SEXP eetaSEXP, SEXP RSSSEXP, SEXP sig2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< mat >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< mat >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< mat >::type eeta(eetaSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    rcpp_result_gen = Rcpp::wrap(update_Q(J, K, zeta, tau, phi, eeta, RSS, sig2));
    return rcpp_result_gen;
END_RCPP
}
// update_Lami
cube update_Lami(mat Q, mat F, mat X, int J, int K, int n);
RcppExport SEXP _BCAIA_update_Lami(SEXP QSEXP, SEXP FSEXP, SEXP XSEXP, SEXP JSEXP, SEXP KSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< mat >::type F(FSEXP);
    Rcpp::traits::input_parameter< mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Lami(Q, F, X, J, K, n));
    return rcpp_result_gen;
END_RCPP
}
// update_ZZ_ZZeta
cube update_ZZ_ZZeta(int J, int K, mat Q, mat pphi_m, rowvec ttau, mat ZZ, mat zzeta);
RcppExport SEXP _BCAIA_update_ZZ_ZZeta(SEXP JSEXP, SEXP KSEXP, SEXP QSEXP, SEXP pphi_mSEXP, SEXP ttauSEXP, SEXP ZZSEXP, SEXP zzetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< mat >::type pphi_m(pphi_mSEXP);
    Rcpp::traits::input_parameter< rowvec >::type ttau(ttauSEXP);
    Rcpp::traits::input_parameter< mat >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< mat >::type zzeta(zzetaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_ZZ_ZZeta(J, K, Q, pphi_m, ttau, ZZ, zzeta));
    return rcpp_result_gen;
END_RCPP
}
// pos_phi
double pos_phi(vec t_p, int wj, int wk, int Jsum, double a_phi, mat Lambda, mat zeta, rowvec tau);
RcppExport SEXP _BCAIA_pos_phi(SEXP t_pSEXP, SEXP wjSEXP, SEXP wkSEXP, SEXP JsumSEXP, SEXP a_phiSEXP, SEXP LambdaSEXP, SEXP zetaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type t_p(t_pSEXP);
    Rcpp::traits::input_parameter< int >::type wj(wjSEXP);
    Rcpp::traits::input_parameter< int >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< int >::type Jsum(JsumSEXP);
    Rcpp::traits::input_parameter< double >::type a_phi(a_phiSEXP);
    Rcpp::traits::input_parameter< mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< mat >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(pos_phi(t_p, wj, wk, Jsum, a_phi, Lambda, zeta, tau));
    return rcpp_result_gen;
END_RCPP
}
// update_phi
cube update_phi(int K, int Jsum, mat til_phi_m, mat sig_pro, double a_phi, mat Lambda, mat zeta, rowvec tau, mat acc, mat phi_m, mat nacc, mat true_nacc, int ni, double acc_tar, double delta);
RcppExport SEXP _BCAIA_update_phi(SEXP KSEXP, SEXP JsumSEXP, SEXP til_phi_mSEXP, SEXP sig_proSEXP, SEXP a_phiSEXP, SEXP LambdaSEXP, SEXP zetaSEXP, SEXP tauSEXP, SEXP accSEXP, SEXP phi_mSEXP, SEXP naccSEXP, SEXP true_naccSEXP, SEXP niSEXP, SEXP acc_tarSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type Jsum(JsumSEXP);
    Rcpp::traits::input_parameter< mat >::type til_phi_m(til_phi_mSEXP);
    Rcpp::traits::input_parameter< mat >::type sig_pro(sig_proSEXP);
    Rcpp::traits::input_parameter< double >::type a_phi(a_phiSEXP);
    Rcpp::traits::input_parameter< mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< mat >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< mat >::type acc(accSEXP);
    Rcpp::traits::input_parameter< mat >::type phi_m(phi_mSEXP);
    Rcpp::traits::input_parameter< mat >::type nacc(naccSEXP);
    Rcpp::traits::input_parameter< mat >::type true_nacc(true_naccSEXP);
    Rcpp::traits::input_parameter< int >::type ni(niSEXP);
    Rcpp::traits::input_parameter< double >::type acc_tar(acc_tarSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_phi(K, Jsum, til_phi_m, sig_pro, a_phi, Lambda, zeta, tau, acc, phi_m, nacc, true_nacc, ni, acc_tar, delta));
    return rcpp_result_gen;
END_RCPP
}
// update_tau_GIG
rowvec update_tau_GIG(int K, double a_tau, double b_tau, int Jsum, mat Lambda, mat phi_m, mat zeta);
RcppExport SEXP _BCAIA_update_tau_GIG(SEXP KSEXP, SEXP a_tauSEXP, SEXP b_tauSEXP, SEXP JsumSEXP, SEXP LambdaSEXP, SEXP phi_mSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type b_tau(b_tauSEXP);
    Rcpp::traits::input_parameter< int >::type Jsum(JsumSEXP);
    Rcpp::traits::input_parameter< mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< mat >::type phi_m(phi_mSEXP);
    Rcpp::traits::input_parameter< mat >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_tau_GIG(K, a_tau, b_tau, Jsum, Lambda, phi_m, zeta));
    return rcpp_result_gen;
END_RCPP
}
// pos_F_kp
double pos_F_kp(int n, int J, mat RSS, cube Lambdai, double sig2, double Fkp);
RcppExport SEXP _BCAIA_pos_F_kp(SEXP nSEXP, SEXP JSEXP, SEXP RSSSEXP, SEXP LambdaiSEXP, SEXP sig2SEXP, SEXP FkpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< cube >::type Lambdai(LambdaiSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< double >::type Fkp(FkpSEXP);
    rcpp_result_gen = Rcpp::wrap(pos_F_kp(n, J, RSS, Lambdai, sig2, Fkp));
    return rcpp_result_gen;
END_RCPP
}
// update_F_kp_MCMC_signswitching
cube update_F_kp_MCMC_signswitching(int n, int J, int K, int P, mat F, mat Q, mat X, mat sig_pro_Fkp, double sig2, mat RSS, mat nacc_Fkp, mat true_nacc_Fkp, double acc_tar, int ni, double gamma_adap, mat loglambda_adap, mat mu_adap);
RcppExport SEXP _BCAIA_update_F_kp_MCMC_signswitching(SEXP nSEXP, SEXP JSEXP, SEXP KSEXP, SEXP PSEXP, SEXP FSEXP, SEXP QSEXP, SEXP XSEXP, SEXP sig_pro_FkpSEXP, SEXP sig2SEXP, SEXP RSSSEXP, SEXP nacc_FkpSEXP, SEXP true_nacc_FkpSEXP, SEXP acc_tarSEXP, SEXP niSEXP, SEXP gamma_adapSEXP, SEXP loglambda_adapSEXP, SEXP mu_adapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< mat >::type F(FSEXP);
    Rcpp::traits::input_parameter< mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< mat >::type sig_pro_Fkp(sig_pro_FkpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< mat >::type nacc_Fkp(nacc_FkpSEXP);
    Rcpp::traits::input_parameter< mat >::type true_nacc_Fkp(true_nacc_FkpSEXP);
    Rcpp::traits::input_parameter< double >::type acc_tar(acc_tarSEXP);
    Rcpp::traits::input_parameter< int >::type ni(niSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_adap(gamma_adapSEXP);
    Rcpp::traits::input_parameter< mat >::type loglambda_adap(loglambda_adapSEXP);
    Rcpp::traits::input_parameter< mat >::type mu_adap(mu_adapSEXP);
    rcpp_result_gen = Rcpp::wrap(update_F_kp_MCMC_signswitching(n, J, K, P, F, Q, X, sig_pro_Fkp, sig2, RSS, nacc_Fkp, true_nacc_Fkp, acc_tar, ni, gamma_adap, loglambda_adap, mu_adap));
    return rcpp_result_gen;
END_RCPP
}
// update_RSS
mat update_RSS(mat ystar, cube Lambdaiarray, mat eta, int n, int J, mat rij, mat alphaij);
RcppExport SEXP _BCAIA_update_RSS(SEXP ystarSEXP, SEXP LambdaiarraySEXP, SEXP etaSEXP, SEXP nSEXP, SEXP JSEXP, SEXP rijSEXP, SEXP alphaijSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type ystar(ystarSEXP);
    Rcpp::traits::input_parameter< cube >::type Lambdaiarray(LambdaiarraySEXP);
    Rcpp::traits::input_parameter< mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< mat >::type rij(rijSEXP);
    Rcpp::traits::input_parameter< mat >::type alphaij(alphaijSEXP);
    rcpp_result_gen = Rcpp::wrap(update_RSS(ystar, Lambdaiarray, eta, n, J, rij, alphaij));
    return rcpp_result_gen;
END_RCPP
}
// update_Delta
mat update_Delta(int K, cube Lambdai, double sig2, int n, mat RSS);
RcppExport SEXP _BCAIA_update_Delta(SEXP KSEXP, SEXP LambdaiSEXP, SEXP sig2SEXP, SEXP nSEXP, SEXP RSSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< cube >::type Lambdai(LambdaiSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Delta(K, Lambdai, sig2, n, RSS));
    return rcpp_result_gen;
END_RCPP
}
// update_Si12
mat update_Si12(int Lr, int n, rowvec ri, rowvec xi, double ur2, double nu_r, rowvec w_l_r, rowvec psi_r);
RcppExport SEXP _BCAIA_update_Si12(SEXP LrSEXP, SEXP nSEXP, SEXP riSEXP, SEXP xiSEXP, SEXP ur2SEXP, SEXP nu_rSEXP, SEXP w_l_rSEXP, SEXP psi_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< rowvec >::type ri(riSEXP);
    Rcpp::traits::input_parameter< rowvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type ur2(ur2SEXP);
    Rcpp::traits::input_parameter< double >::type nu_r(nu_rSEXP);
    Rcpp::traits::input_parameter< rowvec >::type w_l_r(w_l_rSEXP);
    Rcpp::traits::input_parameter< rowvec >::type psi_r(psi_rSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Si12(Lr, n, ri, xi, ur2, nu_r, w_l_r, psi_r));
    return rcpp_result_gen;
END_RCPP
}
// update_xi
rowvec update_xi(int Lr, rowvec ri, rowvec Si1, rowvec Si2, double a_xi, double sig2_xi_r, rowvec w_l_r, double nu_r, double ur2);
RcppExport SEXP _BCAIA_update_xi(SEXP LrSEXP, SEXP riSEXP, SEXP Si1SEXP, SEXP Si2SEXP, SEXP a_xiSEXP, SEXP sig2_xi_rSEXP, SEXP w_l_rSEXP, SEXP nu_rSEXP, SEXP ur2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< rowvec >::type ri(riSEXP);
    Rcpp::traits::input_parameter< rowvec >::type Si1(Si1SEXP);
    Rcpp::traits::input_parameter< rowvec >::type Si2(Si2SEXP);
    Rcpp::traits::input_parameter< double >::type a_xi(a_xiSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_xi_r(sig2_xi_rSEXP);
    Rcpp::traits::input_parameter< rowvec >::type w_l_r(w_l_rSEXP);
    Rcpp::traits::input_parameter< double >::type nu_r(nu_rSEXP);
    Rcpp::traits::input_parameter< double >::type ur2(ur2SEXP);
    rcpp_result_gen = Rcpp::wrap(update_xi(Lr, ri, Si1, Si2, a_xi, sig2_xi_r, w_l_r, nu_r, ur2));
    return rcpp_result_gen;
END_RCPP
}
// update_ri
rowvec update_ri(int n, double ur2, double J, double sig2, mat RSS, rowvec Si1, rowvec Si2, double nu_r, rowvec xi, rowvec w_l_r);
RcppExport SEXP _BCAIA_update_ri(SEXP nSEXP, SEXP ur2SEXP, SEXP JSEXP, SEXP sig2SEXP, SEXP RSSSEXP, SEXP Si1SEXP, SEXP Si2SEXP, SEXP nu_rSEXP, SEXP xiSEXP, SEXP w_l_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type ur2(ur2SEXP);
    Rcpp::traits::input_parameter< double >::type J(JSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< rowvec >::type Si1(Si1SEXP);
    Rcpp::traits::input_parameter< rowvec >::type Si2(Si2SEXP);
    Rcpp::traits::input_parameter< double >::type nu_r(nu_rSEXP);
    Rcpp::traits::input_parameter< rowvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< rowvec >::type w_l_r(w_l_rSEXP);
    rcpp_result_gen = Rcpp::wrap(update_ri(n, ur2, J, sig2, RSS, Si1, Si2, nu_r, xi, w_l_r));
    return rcpp_result_gen;
END_RCPP
}
// poswrt
double poswrt(double winput, rowvec riinput, double sumSi1lSi21, double sumSi1lSi20, double sig2, double a_w_r, double b_w_r, double xi_l_rinput, double nu_r);
RcppExport SEXP _BCAIA_poswrt(SEXP winputSEXP, SEXP riinputSEXP, SEXP sumSi1lSi21SEXP, SEXP sumSi1lSi20SEXP, SEXP sig2SEXP, SEXP a_w_rSEXP, SEXP b_w_rSEXP, SEXP xi_l_rinputSEXP, SEXP nu_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type winput(winputSEXP);
    Rcpp::traits::input_parameter< rowvec >::type riinput(riinputSEXP);
    Rcpp::traits::input_parameter< double >::type sumSi1lSi21(sumSi1lSi21SEXP);
    Rcpp::traits::input_parameter< double >::type sumSi1lSi20(sumSi1lSi20SEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< double >::type a_w_r(a_w_rSEXP);
    Rcpp::traits::input_parameter< double >::type b_w_r(b_w_rSEXP);
    Rcpp::traits::input_parameter< double >::type xi_l_rinput(xi_l_rinputSEXP);
    Rcpp::traits::input_parameter< double >::type nu_r(nu_rSEXP);
    rcpp_result_gen = Rcpp::wrap(poswrt(winput, riinput, sumSi1lSi21, sumSi1lSi20, sig2, a_w_r, b_w_r, xi_l_rinput, nu_r));
    return rcpp_result_gen;
END_RCPP
}
// update_w_r_new
mat update_w_r_new(rowvec w_r, int Lr, rowvec Si1, rowvec Si2, double a_w_r, double b_w_r, rowvec sig_pro_wlr, rowvec ri, rowvec loglbd_wr, double sig2, rowvec xi_l_r, double nu_r, rowvec nacc_w_r, rowvec true_nacc_w_r, double gamma_adap, double acc_tar, rowvec mu_adap_w_r, int n);
RcppExport SEXP _BCAIA_update_w_r_new(SEXP w_rSEXP, SEXP LrSEXP, SEXP Si1SEXP, SEXP Si2SEXP, SEXP a_w_rSEXP, SEXP b_w_rSEXP, SEXP sig_pro_wlrSEXP, SEXP riSEXP, SEXP loglbd_wrSEXP, SEXP sig2SEXP, SEXP xi_l_rSEXP, SEXP nu_rSEXP, SEXP nacc_w_rSEXP, SEXP true_nacc_w_rSEXP, SEXP gamma_adapSEXP, SEXP acc_tarSEXP, SEXP mu_adap_w_rSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< rowvec >::type w_r(w_rSEXP);
    Rcpp::traits::input_parameter< int >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< rowvec >::type Si1(Si1SEXP);
    Rcpp::traits::input_parameter< rowvec >::type Si2(Si2SEXP);
    Rcpp::traits::input_parameter< double >::type a_w_r(a_w_rSEXP);
    Rcpp::traits::input_parameter< double >::type b_w_r(b_w_rSEXP);
    Rcpp::traits::input_parameter< rowvec >::type sig_pro_wlr(sig_pro_wlrSEXP);
    Rcpp::traits::input_parameter< rowvec >::type ri(riSEXP);
    Rcpp::traits::input_parameter< rowvec >::type loglbd_wr(loglbd_wrSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type xi_l_r(xi_l_rSEXP);
    Rcpp::traits::input_parameter< double >::type nu_r(nu_rSEXP);
    Rcpp::traits::input_parameter< rowvec >::type nacc_w_r(nacc_w_rSEXP);
    Rcpp::traits::input_parameter< rowvec >::type true_nacc_w_r(true_nacc_w_rSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_adap(gamma_adapSEXP);
    Rcpp::traits::input_parameter< double >::type acc_tar(acc_tarSEXP);
    Rcpp::traits::input_parameter< rowvec >::type mu_adap_w_r(mu_adap_w_rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(update_w_r_new(w_r, Lr, Si1, Si2, a_w_r, b_w_r, sig_pro_wlr, ri, loglbd_wr, sig2, xi_l_r, nu_r, nacc_w_r, true_nacc_w_r, gamma_adap, acc_tar, mu_adap_w_r, n));
    return rcpp_result_gen;
END_RCPP
}
// update_psi_a
rowvec update_psi_a(int Lalpha, rowvec Sj1, rowvec Sj2, double a_psi_alpha);
RcppExport SEXP _BCAIA_update_psi_a(SEXP LalphaSEXP, SEXP Sj1SEXP, SEXP Sj2SEXP, SEXP a_psi_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Lalpha(LalphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type Sj1(Sj1SEXP);
    Rcpp::traits::input_parameter< rowvec >::type Sj2(Sj2SEXP);
    Rcpp::traits::input_parameter< double >::type a_psi_alpha(a_psi_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_psi_a(Lalpha, Sj1, Sj2, a_psi_alpha));
    return rcpp_result_gen;
END_RCPP
}
// poswt
double poswt(double winput, mat RSSinput, double sumSjlSj21, double sumSjlSj20, double sig2, double a_w_alpha, double b_w_alpha, double xi_l_ainput, double nu_a);
RcppExport SEXP _BCAIA_poswt(SEXP winputSEXP, SEXP RSSinputSEXP, SEXP sumSjlSj21SEXP, SEXP sumSjlSj20SEXP, SEXP sig2SEXP, SEXP a_w_alphaSEXP, SEXP b_w_alphaSEXP, SEXP xi_l_ainputSEXP, SEXP nu_aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type winput(winputSEXP);
    Rcpp::traits::input_parameter< mat >::type RSSinput(RSSinputSEXP);
    Rcpp::traits::input_parameter< double >::type sumSjlSj21(sumSjlSj21SEXP);
    Rcpp::traits::input_parameter< double >::type sumSjlSj20(sumSjlSj20SEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< double >::type a_w_alpha(a_w_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type b_w_alpha(b_w_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type xi_l_ainput(xi_l_ainputSEXP);
    Rcpp::traits::input_parameter< double >::type nu_a(nu_aSEXP);
    rcpp_result_gen = Rcpp::wrap(poswt(winput, RSSinput, sumSjlSj21, sumSjlSj20, sig2, a_w_alpha, b_w_alpha, xi_l_ainput, nu_a));
    return rcpp_result_gen;
END_RCPP
}
// update_w_a
mat update_w_a(rowvec w_a, int Lalpha, rowvec Sj1, rowvec Sj2, double a_w_alpha, double b_w_alpha, rowvec sig_pro_wla, mat RSS, rowvec loglbd_wa, double sig2, rowvec xi_l_a, double nu_a, rowvec nacc_w_a, rowvec true_nacc_w_a, double gamma_adap, double acc_tar, rowvec mu_adap_w_a);
RcppExport SEXP _BCAIA_update_w_a(SEXP w_aSEXP, SEXP LalphaSEXP, SEXP Sj1SEXP, SEXP Sj2SEXP, SEXP a_w_alphaSEXP, SEXP b_w_alphaSEXP, SEXP sig_pro_wlaSEXP, SEXP RSSSEXP, SEXP loglbd_waSEXP, SEXP sig2SEXP, SEXP xi_l_aSEXP, SEXP nu_aSEXP, SEXP nacc_w_aSEXP, SEXP true_nacc_w_aSEXP, SEXP gamma_adapSEXP, SEXP acc_tarSEXP, SEXP mu_adap_w_aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< rowvec >::type w_a(w_aSEXP);
    Rcpp::traits::input_parameter< int >::type Lalpha(LalphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type Sj1(Sj1SEXP);
    Rcpp::traits::input_parameter< rowvec >::type Sj2(Sj2SEXP);
    Rcpp::traits::input_parameter< double >::type a_w_alpha(a_w_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type b_w_alpha(b_w_alphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type sig_pro_wla(sig_pro_wlaSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< rowvec >::type loglbd_wa(loglbd_waSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type xi_l_a(xi_l_aSEXP);
    Rcpp::traits::input_parameter< double >::type nu_a(nu_aSEXP);
    Rcpp::traits::input_parameter< rowvec >::type nacc_w_a(nacc_w_aSEXP);
    Rcpp::traits::input_parameter< rowvec >::type true_nacc_w_a(true_nacc_w_aSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_adap(gamma_adapSEXP);
    Rcpp::traits::input_parameter< double >::type acc_tar(acc_tarSEXP);
    Rcpp::traits::input_parameter< rowvec >::type mu_adap_w_a(mu_adap_w_aSEXP);
    rcpp_result_gen = Rcpp::wrap(update_w_a(w_a, Lalpha, Sj1, Sj2, a_w_alpha, b_w_alpha, sig_pro_wla, RSS, loglbd_wa, sig2, xi_l_a, nu_a, nacc_w_a, true_nacc_w_a, gamma_adap, acc_tar, mu_adap_w_a));
    return rcpp_result_gen;
END_RCPP
}
// update_Sj12
mat update_Sj12(mat RSS, int J, int Lalpha, rowvec xi_alpha, double nu_alpha, rowvec w_l_a, rowvec psi_a, double sig2);
RcppExport SEXP _BCAIA_update_Sj12(SEXP RSSSEXP, SEXP JSEXP, SEXP LalphaSEXP, SEXP xi_alphaSEXP, SEXP nu_alphaSEXP, SEXP w_l_aSEXP, SEXP psi_aSEXP, SEXP sig2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type Lalpha(LalphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type xi_alpha(xi_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type nu_alpha(nu_alphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type w_l_a(w_l_aSEXP);
    Rcpp::traits::input_parameter< rowvec >::type psi_a(psi_aSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    rcpp_result_gen = Rcpp::wrap(update_Sj12(RSS, J, Lalpha, xi_alpha, nu_alpha, w_l_a, psi_a, sig2));
    return rcpp_result_gen;
END_RCPP
}
// update_xi_alpha
rowvec update_xi_alpha(int Lalpha, int n, int J, mat RSS, rowvec Sj1, rowvec Sj2, double u2_alpha, double a_xi_alpha, rowvec w_l_a, double sig2, double nu_alpha);
RcppExport SEXP _BCAIA_update_xi_alpha(SEXP LalphaSEXP, SEXP nSEXP, SEXP JSEXP, SEXP RSSSEXP, SEXP Sj1SEXP, SEXP Sj2SEXP, SEXP u2_alphaSEXP, SEXP a_xi_alphaSEXP, SEXP w_l_aSEXP, SEXP sig2SEXP, SEXP nu_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Lalpha(LalphaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< rowvec >::type Sj1(Sj1SEXP);
    Rcpp::traits::input_parameter< rowvec >::type Sj2(Sj2SEXP);
    Rcpp::traits::input_parameter< double >::type u2_alpha(u2_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type a_xi_alpha(a_xi_alphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type w_l_a(w_l_aSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< double >::type nu_alpha(nu_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_xi_alpha(Lalpha, n, J, RSS, Sj1, Sj2, u2_alpha, a_xi_alpha, w_l_a, sig2, nu_alpha));
    return rcpp_result_gen;
END_RCPP
}
// update_psi_w_r
cube update_psi_w_r(int m, int Lr, mat Si1, mat Si2, double a_w, double b_w, double a_psi_r);
RcppExport SEXP _BCAIA_update_psi_w_r(SEXP mSEXP, SEXP LrSEXP, SEXP Si1SEXP, SEXP Si2SEXP, SEXP a_wSEXP, SEXP b_wSEXP, SEXP a_psi_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< mat >::type Si1(Si1SEXP);
    Rcpp::traits::input_parameter< mat >::type Si2(Si2SEXP);
    Rcpp::traits::input_parameter< double >::type a_w(a_wSEXP);
    Rcpp::traits::input_parameter< double >::type b_w(b_wSEXP);
    Rcpp::traits::input_parameter< double >::type a_psi_r(a_psi_rSEXP);
    rcpp_result_gen = Rcpp::wrap(update_psi_w_r(m, Lr, Si1, Si2, a_w, b_w, a_psi_r));
    return rcpp_result_gen;
END_RCPP
}
// update_Si12_grp
cube update_Si12_grp(int Lr, int n, int m, mat ri, mat xi, double ur2, rowvec nu_r, mat w_l_r_m, mat psi_r_m);
RcppExport SEXP _BCAIA_update_Si12_grp(SEXP LrSEXP, SEXP nSEXP, SEXP mSEXP, SEXP riSEXP, SEXP xiSEXP, SEXP ur2SEXP, SEXP nu_rSEXP, SEXP w_l_r_mSEXP, SEXP psi_r_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< mat >::type ri(riSEXP);
    Rcpp::traits::input_parameter< mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type ur2(ur2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type nu_r(nu_rSEXP);
    Rcpp::traits::input_parameter< mat >::type w_l_r_m(w_l_r_mSEXP);
    Rcpp::traits::input_parameter< mat >::type psi_r_m(psi_r_mSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Si12_grp(Lr, n, m, ri, xi, ur2, nu_r, w_l_r_m, psi_r_m));
    return rcpp_result_gen;
END_RCPP
}
// update_xi_grp
mat update_xi_grp(int m, int Lr, mat ri, mat Si1, mat Si2, rowvec a_xi, rowvec sig2_xi_r, mat w_l_r_m, mat psi_r_m, rowvec nu_r, double ur2);
RcppExport SEXP _BCAIA_update_xi_grp(SEXP mSEXP, SEXP LrSEXP, SEXP riSEXP, SEXP Si1SEXP, SEXP Si2SEXP, SEXP a_xiSEXP, SEXP sig2_xi_rSEXP, SEXP w_l_r_mSEXP, SEXP psi_r_mSEXP, SEXP nu_rSEXP, SEXP ur2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< mat >::type ri(riSEXP);
    Rcpp::traits::input_parameter< mat >::type Si1(Si1SEXP);
    Rcpp::traits::input_parameter< mat >::type Si2(Si2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type a_xi(a_xiSEXP);
    Rcpp::traits::input_parameter< rowvec >::type sig2_xi_r(sig2_xi_rSEXP);
    Rcpp::traits::input_parameter< mat >::type w_l_r_m(w_l_r_mSEXP);
    Rcpp::traits::input_parameter< mat >::type psi_r_m(psi_r_mSEXP);
    Rcpp::traits::input_parameter< rowvec >::type nu_r(nu_rSEXP);
    Rcpp::traits::input_parameter< double >::type ur2(ur2SEXP);
    rcpp_result_gen = Rcpp::wrap(update_xi_grp(m, Lr, ri, Si1, Si2, a_xi, sig2_xi_r, w_l_r_m, psi_r_m, nu_r, ur2));
    return rcpp_result_gen;
END_RCPP
}
// update_ri_grp
mat update_ri_grp(int m, int n, double ur2, rowvec J, rowvec sig2, mat RSS, rowvec J_bound, mat Si1, mat Si2, rowvec nu_r, mat xi, mat w_l_r_m);
RcppExport SEXP _BCAIA_update_ri_grp(SEXP mSEXP, SEXP nSEXP, SEXP ur2SEXP, SEXP JSEXP, SEXP sig2SEXP, SEXP RSSSEXP, SEXP J_boundSEXP, SEXP Si1SEXP, SEXP Si2SEXP, SEXP nu_rSEXP, SEXP xiSEXP, SEXP w_l_r_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type ur2(ur2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type J(JSEXP);
    Rcpp::traits::input_parameter< rowvec >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< rowvec >::type J_bound(J_boundSEXP);
    Rcpp::traits::input_parameter< mat >::type Si1(Si1SEXP);
    Rcpp::traits::input_parameter< mat >::type Si2(Si2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type nu_r(nu_rSEXP);
    Rcpp::traits::input_parameter< mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< mat >::type w_l_r_m(w_l_r_mSEXP);
    rcpp_result_gen = Rcpp::wrap(update_ri_grp(m, n, ur2, J, sig2, RSS, J_bound, Si1, Si2, nu_r, xi, w_l_r_m));
    return rcpp_result_gen;
END_RCPP
}
// update_psi_w
cube update_psi_w(int m, int Lalpha, rowvec J_bound, mat Sij1, mat Sij2, double a_w_alpha, double b_w_alpha, double a_psi_alpha);
RcppExport SEXP _BCAIA_update_psi_w(SEXP mSEXP, SEXP LalphaSEXP, SEXP J_boundSEXP, SEXP Sij1SEXP, SEXP Sij2SEXP, SEXP a_w_alphaSEXP, SEXP b_w_alphaSEXP, SEXP a_psi_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type Lalpha(LalphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type J_bound(J_boundSEXP);
    Rcpp::traits::input_parameter< mat >::type Sij1(Sij1SEXP);
    Rcpp::traits::input_parameter< mat >::type Sij2(Sij2SEXP);
    Rcpp::traits::input_parameter< double >::type a_w_alpha(a_w_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type b_w_alpha(b_w_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type a_psi_alpha(a_psi_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_psi_w(m, Lalpha, J_bound, Sij1, Sij2, a_w_alpha, b_w_alpha, a_psi_alpha));
    return rcpp_result_gen;
END_RCPP
}
// update_Sij12
cube update_Sij12(mat RSS, int s, int Jsum, int Lalpha, mat xi_alpha, rowvec nu_alpha, mat w_l_a_m, mat psi_a_m, rowvec M, rowvec sig2, rowvec S);
RcppExport SEXP _BCAIA_update_Sij12(SEXP RSSSEXP, SEXP sSEXP, SEXP JsumSEXP, SEXP LalphaSEXP, SEXP xi_alphaSEXP, SEXP nu_alphaSEXP, SEXP w_l_a_mSEXP, SEXP psi_a_mSEXP, SEXP MSEXP, SEXP sig2SEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type Jsum(JsumSEXP);
    Rcpp::traits::input_parameter< int >::type Lalpha(LalphaSEXP);
    Rcpp::traits::input_parameter< mat >::type xi_alpha(xi_alphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type nu_alpha(nu_alphaSEXP);
    Rcpp::traits::input_parameter< mat >::type w_l_a_m(w_l_a_mSEXP);
    Rcpp::traits::input_parameter< mat >::type psi_a_m(psi_a_mSEXP);
    Rcpp::traits::input_parameter< rowvec >::type M(MSEXP);
    Rcpp::traits::input_parameter< rowvec >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Sij12(RSS, s, Jsum, Lalpha, xi_alpha, nu_alpha, w_l_a_m, psi_a_m, M, sig2, S));
    return rcpp_result_gen;
END_RCPP
}
// update_xi_alpha_grp
mat update_xi_alpha_grp(int Lalpha, int Jsum, mat RSS, mat IIJ1, mat IIJ2, rowvec u2_alpha, rowvec a_xi_alpha, rowvec M, mat w_l_a_m, rowvec sig2, rowvec nu_alpha);
RcppExport SEXP _BCAIA_update_xi_alpha_grp(SEXP LalphaSEXP, SEXP JsumSEXP, SEXP RSSSEXP, SEXP IIJ1SEXP, SEXP IIJ2SEXP, SEXP u2_alphaSEXP, SEXP a_xi_alphaSEXP, SEXP MSEXP, SEXP w_l_a_mSEXP, SEXP sig2SEXP, SEXP nu_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Lalpha(LalphaSEXP);
    Rcpp::traits::input_parameter< int >::type Jsum(JsumSEXP);
    Rcpp::traits::input_parameter< mat >::type RSS(RSSSEXP);
    Rcpp::traits::input_parameter< mat >::type IIJ1(IIJ1SEXP);
    Rcpp::traits::input_parameter< mat >::type IIJ2(IIJ2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type u2_alpha(u2_alphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type a_xi_alpha(a_xi_alphaSEXP);
    Rcpp::traits::input_parameter< rowvec >::type M(MSEXP);
    Rcpp::traits::input_parameter< mat >::type w_l_a_m(w_l_a_mSEXP);
    Rcpp::traits::input_parameter< rowvec >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< rowvec >::type nu_alpha(nu_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_xi_alpha_grp(Lalpha, Jsum, RSS, IIJ1, IIJ2, u2_alpha, a_xi_alpha, M, w_l_a_m, sig2, nu_alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BCAIA_dmvnrm_arma_mc", (DL_FUNC) &_BCAIA_dmvnrm_arma_mc, 4},
    {"_BCAIA_dnormLog2", (DL_FUNC) &_BCAIA_dnormLog2, 3},
    {"_BCAIA_rgigRcpp", (DL_FUNC) &_BCAIA_rgigRcpp, 3},
    {"_BCAIA_seq_cpp", (DL_FUNC) &_BCAIA_seq_cpp, 2},
    {"_BCAIA_mvrnormArma", (DL_FUNC) &_BCAIA_mvrnormArma, 3},
    {"_BCAIA_cpp_inv", (DL_FUNC) &_BCAIA_cpp_inv, 1},
    {"_BCAIA_update_ystar", (DL_FUNC) &_BCAIA_update_ystar, 6},
    {"_BCAIA_update_sig2", (DL_FUNC) &_BCAIA_update_sig2, 5},
    {"_BCAIA_update_Q", (DL_FUNC) &_BCAIA_update_Q, 8},
    {"_BCAIA_update_Lami", (DL_FUNC) &_BCAIA_update_Lami, 6},
    {"_BCAIA_update_ZZ_ZZeta", (DL_FUNC) &_BCAIA_update_ZZ_ZZeta, 7},
    {"_BCAIA_pos_phi", (DL_FUNC) &_BCAIA_pos_phi, 8},
    {"_BCAIA_update_phi", (DL_FUNC) &_BCAIA_update_phi, 15},
    {"_BCAIA_update_tau_GIG", (DL_FUNC) &_BCAIA_update_tau_GIG, 7},
    {"_BCAIA_pos_F_kp", (DL_FUNC) &_BCAIA_pos_F_kp, 6},
    {"_BCAIA_update_F_kp_MCMC_signswitching", (DL_FUNC) &_BCAIA_update_F_kp_MCMC_signswitching, 17},
    {"_BCAIA_update_RSS", (DL_FUNC) &_BCAIA_update_RSS, 7},
    {"_BCAIA_update_Delta", (DL_FUNC) &_BCAIA_update_Delta, 5},
    {"_BCAIA_update_Si12", (DL_FUNC) &_BCAIA_update_Si12, 8},
    {"_BCAIA_update_xi", (DL_FUNC) &_BCAIA_update_xi, 9},
    {"_BCAIA_update_ri", (DL_FUNC) &_BCAIA_update_ri, 10},
    {"_BCAIA_poswrt", (DL_FUNC) &_BCAIA_poswrt, 9},
    {"_BCAIA_update_w_r_new", (DL_FUNC) &_BCAIA_update_w_r_new, 18},
    {"_BCAIA_update_psi_a", (DL_FUNC) &_BCAIA_update_psi_a, 4},
    {"_BCAIA_poswt", (DL_FUNC) &_BCAIA_poswt, 9},
    {"_BCAIA_update_w_a", (DL_FUNC) &_BCAIA_update_w_a, 17},
    {"_BCAIA_update_Sj12", (DL_FUNC) &_BCAIA_update_Sj12, 8},
    {"_BCAIA_update_xi_alpha", (DL_FUNC) &_BCAIA_update_xi_alpha, 11},
    {"_BCAIA_update_psi_w_r", (DL_FUNC) &_BCAIA_update_psi_w_r, 7},
    {"_BCAIA_update_Si12_grp", (DL_FUNC) &_BCAIA_update_Si12_grp, 9},
    {"_BCAIA_update_xi_grp", (DL_FUNC) &_BCAIA_update_xi_grp, 11},
    {"_BCAIA_update_ri_grp", (DL_FUNC) &_BCAIA_update_ri_grp, 12},
    {"_BCAIA_update_psi_w", (DL_FUNC) &_BCAIA_update_psi_w, 8},
    {"_BCAIA_update_Sij12", (DL_FUNC) &_BCAIA_update_Sij12, 11},
    {"_BCAIA_update_xi_alpha_grp", (DL_FUNC) &_BCAIA_update_xi_alpha_grp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_BCAIA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
