# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma_mc <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_BCAIA_dmvnrm_arma_mc`, x, mean, sigma, logd)
}

dnormLog2 <- function(x, means, sds) {
    .Call(`_BCAIA_dnormLog2`, x, means, sds)
}

rgigRcpp <- function(lam, chi, psi) {
    .Call(`_BCAIA_rgigRcpp`, lam, chi, psi)
}

seq_cpp <- function(locppid, hicppid) {
    .Call(`_BCAIA_seq_cpp`, locppid, hicppid)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_BCAIA_mvrnormArma`, n, mu, sigma)
}

cpp_inv <- function(A) {
    .Call(`_BCAIA_cpp_inv`, A)
}

update_ystar <- function(logY, logY1, n, J, RSS, sig2) {
    .Call(`_BCAIA_update_ystar`, logY, logY1, n, J, RSS, sig2)
}

update_sig2 <- function(n, J, RSS, a_sig, b_sig) {
    .Call(`_BCAIA_update_sig2`, n, J, RSS, a_sig, b_sig)
}

update_Q <- function(J, K, zeta, tau, phi, eeta, RSS, sig2) {
    .Call(`_BCAIA_update_Q`, J, K, zeta, tau, phi, eeta, RSS, sig2)
}

update_Lami <- function(Q, F, X, J, K, n) {
    .Call(`_BCAIA_update_Lami`, Q, F, X, J, K, n)
}

update_ZZ_ZZeta <- function(J, K, Q, pphi_m, ttau, ZZ, zzeta) {
    .Call(`_BCAIA_update_ZZ_ZZeta`, J, K, Q, pphi_m, ttau, ZZ, zzeta)
}

pos_phi <- function(t_p, wj, wk, Jsum, a_phi, Lambda, zeta, tau) {
    .Call(`_BCAIA_pos_phi`, t_p, wj, wk, Jsum, a_phi, Lambda, zeta, tau)
}

update_phi <- function(K, Jsum, til_phi_m, sig_pro, a_phi, Lambda, zeta, tau, acc, phi_m, nacc, true_nacc, ni, acc_tar, delta) {
    .Call(`_BCAIA_update_phi`, K, Jsum, til_phi_m, sig_pro, a_phi, Lambda, zeta, tau, acc, phi_m, nacc, true_nacc, ni, acc_tar, delta)
}

update_tau_GIG <- function(K, a_tau, b_tau, Jsum, Lambda, phi_m, zeta) {
    .Call(`_BCAIA_update_tau_GIG`, K, a_tau, b_tau, Jsum, Lambda, phi_m, zeta)
}

pos_F_kp <- function(n, J, RSS, Lambdai, sig2, Fkp) {
    .Call(`_BCAIA_pos_F_kp`, n, J, RSS, Lambdai, sig2, Fkp)
}

update_F_kp_MCMC_signswitching <- function(n, J, K, P, F, Q, X, sig_pro_Fkp, sig2, RSS, nacc_Fkp, true_nacc_Fkp, acc_tar, ni, gamma_adap, loglambda_adap, mu_adap) {
    .Call(`_BCAIA_update_F_kp_MCMC_signswitching`, n, J, K, P, F, Q, X, sig_pro_Fkp, sig2, RSS, nacc_Fkp, true_nacc_Fkp, acc_tar, ni, gamma_adap, loglambda_adap, mu_adap)
}

update_RSS <- function(ystar, Lambdaiarray, eta, n, J, rij, alphaij) {
    .Call(`_BCAIA_update_RSS`, ystar, Lambdaiarray, eta, n, J, rij, alphaij)
}

update_Delta <- function(K, Lambdai, sig2, n, RSS) {
    .Call(`_BCAIA_update_Delta`, K, Lambdai, sig2, n, RSS)
}

update_Si12 <- function(Lr, n, ri, xi, ur2, nu_r, w_l_r, psi_r) {
    .Call(`_BCAIA_update_Si12`, Lr, n, ri, xi, ur2, nu_r, w_l_r, psi_r)
}

update_xi <- function(Lr, ri, Si1, Si2, a_xi, sig2_xi_r, w_l_r, nu_r, ur2) {
    .Call(`_BCAIA_update_xi`, Lr, ri, Si1, Si2, a_xi, sig2_xi_r, w_l_r, nu_r, ur2)
}

update_ri <- function(n, ur2, J, sig2, RSS, Si1, Si2, nu_r, xi, w_l_r) {
    .Call(`_BCAIA_update_ri`, n, ur2, J, sig2, RSS, Si1, Si2, nu_r, xi, w_l_r)
}

poswrt <- function(winput, riinput, sumSi1lSi21, sumSi1lSi20, sig2, a_w_r, b_w_r, xi_l_rinput, nu_r) {
    .Call(`_BCAIA_poswrt`, winput, riinput, sumSi1lSi21, sumSi1lSi20, sig2, a_w_r, b_w_r, xi_l_rinput, nu_r)
}

update_w_r_new <- function(w_r, Lr, Si1, Si2, a_w_r, b_w_r, sig_pro_wlr, ri, loglbd_wr, sig2, xi_l_r, nu_r, nacc_w_r, true_nacc_w_r, gamma_adap, acc_tar, mu_adap_w_r, n) {
    .Call(`_BCAIA_update_w_r_new`, w_r, Lr, Si1, Si2, a_w_r, b_w_r, sig_pro_wlr, ri, loglbd_wr, sig2, xi_l_r, nu_r, nacc_w_r, true_nacc_w_r, gamma_adap, acc_tar, mu_adap_w_r, n)
}

update_psi_a <- function(Lalpha, Sj1, Sj2, a_psi_alpha) {
    .Call(`_BCAIA_update_psi_a`, Lalpha, Sj1, Sj2, a_psi_alpha)
}

poswt <- function(winput, RSSinput, sumSjlSj21, sumSjlSj20, sig2, a_w_alpha, b_w_alpha, xi_l_ainput, nu_a) {
    .Call(`_BCAIA_poswt`, winput, RSSinput, sumSjlSj21, sumSjlSj20, sig2, a_w_alpha, b_w_alpha, xi_l_ainput, nu_a)
}

update_w_a <- function(w_a, Lalpha, Sj1, Sj2, a_w_alpha, b_w_alpha, sig_pro_wla, RSS, loglbd_wa, sig2, xi_l_a, nu_a, nacc_w_a, true_nacc_w_a, gamma_adap, acc_tar, mu_adap_w_a) {
    .Call(`_BCAIA_update_w_a`, w_a, Lalpha, Sj1, Sj2, a_w_alpha, b_w_alpha, sig_pro_wla, RSS, loglbd_wa, sig2, xi_l_a, nu_a, nacc_w_a, true_nacc_w_a, gamma_adap, acc_tar, mu_adap_w_a)
}

update_Sj12 <- function(RSS, J, Lalpha, xi_alpha, nu_alpha, w_l_a, psi_a, sig2) {
    .Call(`_BCAIA_update_Sj12`, RSS, J, Lalpha, xi_alpha, nu_alpha, w_l_a, psi_a, sig2)
}

update_xi_alpha <- function(Lalpha, n, J, RSS, Sj1, Sj2, u2_alpha, a_xi_alpha, w_l_a, sig2, nu_alpha) {
    .Call(`_BCAIA_update_xi_alpha`, Lalpha, n, J, RSS, Sj1, Sj2, u2_alpha, a_xi_alpha, w_l_a, sig2, nu_alpha)
}

update_psi_w_r <- function(m, Lr, Si1, Si2, a_w, b_w, a_psi_r) {
    .Call(`_BCAIA_update_psi_w_r`, m, Lr, Si1, Si2, a_w, b_w, a_psi_r)
}

update_Si12_grp <- function(Lr, n, m, ri, xi, ur2, nu_r, w_l_r_m, psi_r_m) {
    .Call(`_BCAIA_update_Si12_grp`, Lr, n, m, ri, xi, ur2, nu_r, w_l_r_m, psi_r_m)
}

update_xi_grp <- function(m, Lr, ri, Si1, Si2, a_xi, sig2_xi_r, w_l_r_m, psi_r_m, nu_r, ur2) {
    .Call(`_BCAIA_update_xi_grp`, m, Lr, ri, Si1, Si2, a_xi, sig2_xi_r, w_l_r_m, psi_r_m, nu_r, ur2)
}

update_ri_grp <- function(m, n, ur2, J, sig2, RSS, J_bound, Si1, Si2, nu_r, xi, w_l_r_m) {
    .Call(`_BCAIA_update_ri_grp`, m, n, ur2, J, sig2, RSS, J_bound, Si1, Si2, nu_r, xi, w_l_r_m)
}

update_psi_w <- function(m, Lalpha, J_bound, Sij1, Sij2, a_w_alpha, b_w_alpha, a_psi_alpha) {
    .Call(`_BCAIA_update_psi_w`, m, Lalpha, J_bound, Sij1, Sij2, a_w_alpha, b_w_alpha, a_psi_alpha)
}

update_Sij12 <- function(RSS, s, Jsum, Lalpha, xi_alpha, nu_alpha, w_l_a_m, psi_a_m, M, sig2, S) {
    .Call(`_BCAIA_update_Sij12`, RSS, s, Jsum, Lalpha, xi_alpha, nu_alpha, w_l_a_m, psi_a_m, M, sig2, S)
}

update_xi_alpha_grp <- function(Lalpha, Jsum, RSS, IIJ1, IIJ2, u2_alpha, a_xi_alpha, M, w_l_a_m, sig2, nu_alpha) {
    .Call(`_BCAIA_update_xi_alpha_grp`, Lalpha, Jsum, RSS, IIJ1, IIJ2, u2_alpha, a_xi_alpha, M, w_l_a_m, sig2, nu_alpha)
}

